sudo: required

cache:
  directories:
    - $HOME/.composer

services:
  - docker

install:
  - docker-compose pull
  - bin/composer.sh install --prefer-dist

script:
  # Run the tests
  - bin/run_tests.sh
  # Test the console application
  - bin/meetup.sh schedule 1 Test Test '2024-09-07 20:00'
  # See if deptrac can run
  - bin/deptrac.sh
