version: '3'

services:
    web:
        build: docker/web/
        image: matthiasnoback/layers-ports-and-adapters-workshop-web
        volumes:
            - ./:/app
        ports:
            - "127.0.0.1:8080:8080"
        expose:
            - 8080
        user: ${HOST_UID}:${HOST_GID}

    php:
        build: docker/php/
        image: matthiasnoback/layers-ports-and-adapters-workshop-php
        volumes:
            - ./:/app
        environment:
            WEB_HOSTNAME: web
        depends_on:
            - web
        working_dir: /app
        user: ${HOST_UID}:${HOST_GID}

    composer:
        image: composer:latest
        volumes:
          - ./:/app
        user: ${HOST_UID}:${HOST_GID}
